version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: learning_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm run dev"

volumes:
  pgdata:
